[pytest]
addopts = -vs -n auto --alluredir=allure-results --html=reports/report.html --self-contained-html
testpaths = tests
markers =
    regression: Regression test suite
    smoke: Smoke test suite